[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/admin/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
DJANGO_SETTINGS_MODULE = "mtt_gateway.settings"
PYTHONPATH = "/app" 