# Generated by Django 4.2.7 on 2025-07-16 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('panel_type', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('ANALYTICS', 'Analytics'), ('REPORTING', 'Reporting'), ('MONITORING', 'Monitoring'), ('CONFIGURATION', 'Configuration')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_access_level', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('READ_ONLY', 'Read Only')], max_length=20)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('layout_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_panels', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'canasale_admin_panel',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ERPIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('SAP', 'SAP ERP'), ('ORACLE', 'Oracle ERP'), ('DYNAMICS', 'Microsoft Dynamics'), ('NETSUITE', 'NetSuite'), ('QUICKBOOKS', 'QuickBooks'), ('CUSTOM', 'Custom ERP')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_orders', models.BooleanField(default=True)),
                ('sync_customers', models.BooleanField(default=True)),
                ('sync_products', models.BooleanField(default=True)),
                ('sync_payments', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('SYNCING', 'Syncing')], default='INACTIVE', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_integrations', to='merchant.merchant')),
            ],
            options={
                'db_table': 'canasale_erp_integration',
            },
        ),
        migrations.CreateModel(
            name='WebUIComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('WIDGET', 'Widget'), ('CHART', 'Chart'), ('TABLE', 'Table'), ('FORM', 'Form'), ('BUTTON', 'Button'), ('MENU', 'Menu'), ('MODAL', 'Modal')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('refresh_interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=1)),
                ('height', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='canasale.adminpanel')),
            ],
            options={
                'db_table': 'canasale_web_ui_component',
                'indexes': [models.Index(fields=['admin_panel', 'is_active'], name='canasale_we_admin_p_61cb73_idx'), models.Index(fields=['component_type'], name='canasale_we_compone_1bb592_idx'), models.Index(fields=['position_x', 'position_y'], name='canasale_we_positio_e2ddef_idx')],
                'unique_together': {('admin_panel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'canasale_config',
                'indexes': [models.Index(fields=['key'], name='canasale_co_key_d0a7ed_idx'), models.Index(fields=['is_public'], name='canasale_co_is_publ_8b3c63_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('SECURITY', 'Security'), ('PAYMENT', 'Payment'), ('MAINTENANCE', 'Maintenance'), ('PERFORMANCE', 'Performance')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('source_component', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_resolve_after_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'canasale_system_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'status'], name='canasale_sy_alert_t_a8c1c3_idx'), models.Index(fields=['category', 'created_at'], name='canasale_sy_categor_2b7dbc_idx'), models.Index(fields=['status', 'created_at'], name='canasale_sy_status_5f79b6_idx'), models.Index(fields=['assigned_to'], name='canasale_sy_assigne_38932a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewaySetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setup_type', models.CharField(choices=[('QUICK_SETUP', 'Quick Setup'), ('ADVANCED_SETUP', 'Advanced Setup'), ('CUSTOM_SETUP', 'Custom Setup')], max_length=20)),
                ('setup_config', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('total_steps', models.PositiveSmallIntegerField(default=5)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_setups', to='merchant.merchant')),
            ],
            options={
                'db_table': 'canasale_gateway_setup',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='canasale_ga_merchan_964926_idx'), models.Index(fields=['setup_type'], name='canasale_ga_setup_t_57dbe5_idx'), models.Index(fields=['created_at'], name='canasale_ga_created_779a61_idx')],
            },
        ),
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('ORDERS', 'Orders'), ('CUSTOMERS', 'Customers'), ('PRODUCTS', 'Products'), ('PAYMENTS', 'Payments'), ('INVENTORY', 'Inventory')], max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_success', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sync_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('erp_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='canasale.erpintegration')),
            ],
            options={
                'db_table': 'canasale_erp_sync_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['erp_integration', 'started_at'], name='canasale_er_erp_int_5e7ce2_idx'), models.Index(fields=['sync_type', 'status'], name='canasale_er_sync_ty_b54fa9_idx'), models.Index(fields=['started_at'], name='canasale_er_started_8e69b2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='erpintegration',
            index=models.Index(fields=['merchant', 'status'], name='canasale_er_merchan_f7b321_idx'),
        ),
        migrations.AddIndex(
            model_name='erpintegration',
            index=models.Index(fields=['integration_type'], name='canasale_er_integra_1c385f_idx'),
        ),
        migrations.AddIndex(
            model_name='erpintegration',
            index=models.Index(fields=['auto_sync', 'status'], name='canasale_er_auto_sy_390b5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='erpintegration',
            unique_together={('merchant', 'name')},
        ),
        migrations.AddIndex(
            model_name='adminpanel',
            index=models.Index(fields=['panel_type', 'is_active'], name='canasale_ad_panel_t_e596d9_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpanel',
            index=models.Index(fields=['required_access_level'], name='canasale_ad_require_c2f31e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpanel',
            index=models.Index(fields=['sort_order'], name='canasale_ad_sort_or_e0399a_idx'),
        ),
    ]
