# Generated by Django 4.2.7 on 2025-07-16 21:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MayTheToken', max_length=100)),
                ('symbol', models.CharField(default='MTT', max_length=10)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('total_supply', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('chain_id', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MTT Token',
                'verbose_name_plural': 'MTT Tokens',
                'db_table': 'tokens_token',
            },
        ),
        migrations.CreateModel(
            name='TokenTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(blank=True, max_length=42, null=True)),
                ('to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('1E-18'))])),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gas_used', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gas_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('transfer_type', models.CharField(choices=[('SEND', 'Send'), ('RECEIVE', 'Receive'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('REWARD', 'Reward'), ('REFUND', 'Refund'), ('FEE', 'Fee')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
            options={
                'db_table': 'tokens_transfer',
                'indexes': [models.Index(fields=['from_user', 'created_at'], name='tokens_tran_from_us_555dea_idx'), models.Index(fields=['to_user', 'created_at'], name='tokens_tran_to_user_0020dc_idx'), models.Index(fields=['transaction_hash'], name='tokens_tran_transac_a34689_idx'), models.Index(fields=['status', 'created_at'], name='tokens_tran_status_927ac4_idx'), models.Index(fields=['transfer_type'], name='tokens_tran_transfe_63f55c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_eth', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('source', models.CharField(default='internal', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
            options={
                'db_table': 'tokens_price',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token', 'timestamp'], name='tokens_pric_token_i_8081d4_idx'), models.Index(fields=['timestamp'], name='tokens_pric_timesta_7976ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('locked_balance', models.DecimalField(decimal_places=18, default=0, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available_balance', models.DecimalField(decimal_places=18, default=0, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tokens_balance',
                'indexes': [models.Index(fields=['user', 'token'], name='tokens_bala_user_id_364031_idx'), models.Index(fields=['balance'], name='tokens_bala_balance_36019b_idx')],
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='TokenAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spender_address', models.CharField(max_length=42)),
                ('allowance', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
            options={
                'db_table': 'tokens_allowance',
                'indexes': [models.Index(fields=['owner', 'spender_address'], name='tokens_allo_owner_i_5d6cee_idx'), models.Index(fields=['is_active'], name='tokens_allo_is_acti_9c7199_idx')],
                'unique_together': {('token', 'owner', 'spender_address')},
            },
        ),
    ]
